# Generated by Django 4.2.17 on 2025-01-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weatherApi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorites",
            name="country",
            field=models.CharField(default="NS", max_length=255),
        ),
    ]
